version: "3"
networks:
  api_server_default:
    external: true
services:
  api:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 3333
